### ISSUE TITLE
looking forward to  discussion

### ISSUE THREAD

**Issue by Yuuoniy** [Anhang512/WORK#1]
Hi, Anhang512:
     I notice that you are  coping with your AEG project , and I also doing reasearch on this area. So I look forward to have more discussion with you. 
    By the way, I am a undergradute student from SYSU, my graduation project is also about this topic, though  the problem I would like to address maybe is more naive when compared with yours. 
   Since I couldn't find your contact info, I open this issue.

**Comment by Anhang512** [comment]
I‘'m also new to this fied. But I am very happy to disscuss it with you @Yuuoniy. 
My email is anhang@bupt.edu.cn.
